Выполнено ТЗ, 13 спринт
KolesnikovaEV/java-shareit pull request #1
Opened 2023-06-30 17:24 UTC by KolesnikovaEV

2023-07-02 15:34 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2023-07-02 15:34 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +@RequiredArgsConstructor
Аннотация `@Data` уже включает в себя `RequiredArgsConstructor`

https://projectlombok.org/features/Data

2023-07-02 15:34 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +@RequiredArgsConstructor
Аннотация `@Data` уже включает в себя эти три аннотации

2023-07-02 15:34 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryInMemory.java
> +    Map<Long, Item> itemRepository = new HashMap<>();
Необходимы модификаторы доступа

2023-07-02 15:34 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryInMemory.java
> +    }
Почему этот метод пустой?

2023-07-02 15:34 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        allItems.stream().map(mapper::toItemDto).forEach(allItemsDto::add);
почему бы не воспользоваться `.collect(Collectors.toList());`, которым мы уже пользовались в других случаях?

2023-07-02 15:34 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    }
Почему этот метод пустой?

2023-07-02 15:34 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +@RequiredArgsConstructor
Не нужна эта аннотация

2023-07-02 15:34 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryInMemory.java
> +    private Map<Long, User> userRepository = new HashMap<>();
Сюда необходимо добавить модификатор `final`, чтобы указать на то, что коллекцию нельзя менять на другую во время выполнения приложения

2023-07-02 15:34 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryInMemory.java
> +        }
`HashMap` не выбрасывает исключение, если пользователь не найден. Он просто возвращает `null`

2023-07-02 15:34 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryInMemory.java
> +            if (email.equals(userEmail)) {
Если адреса электронной почты имеют разный регистр это не значит, что они отличаются

Пример одинаковых адресов электронной почты: `test@example.com`, `Test@example.com`, `TEST@example.com`.

Так что поиск работает не совсем корректно

2023-07-02 15:34 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +public class UserServiceImpl implements UserService {
Замечания аналогичные `ItemServiceImpl`

2023-07-02 15:34 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/validation/ValidationService.java
> +    }
На самом деле этот метод и метод выше фактически аналогичны. 
Только в одном случае мы ожидаем, что нам вернется `user` с заданным идентификатором, а в другом `null`. Может есть способ их объединить и не дублировать очень похожую логику?

2023-07-02 15:34 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/validation/ValidationService.java
> +        boolean[] result;
Зачем декларация отдельно от инициализации?

2023-07-02 15:34 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/validation/ValidationService.java
> +    public boolean[] checkFieldsForUpdate(User user) {
1. Всегда стоит стремиться к использованию более универсальных коллекций. В данном случае гораздо удобнее было бы работать с `List<Boolean>`
2. Не очень удачно введение связи между идентификаторами элементов в булевском массиве и полями абстракции `User`. У нас может возникнуть необходимость в изменении порядка аргументов, и в таком случае наш код будет продолжать успешно выполняться, но при этом будут происходить логические ошибки, так как мы заводим связь между полями и идентификаторами, которая нигде не задекларирована, и непонятно откуда она вообще берется. Сейчас ты выполняешь этот проект в одиночку, но если бы над ним работала команда, необходимо было бы сообщить всем участникам, что существует такая связь и где она находится, что очень трудозатратно

2023-07-02 15:34 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/validation/ValidationService.java
> +    }
Замечания аналогичные методу для пользователя

2023-07-02 22:23 UTC, KolesnikovaEV commented
Привет! Спасибо за комментарии, вроде все исправила)

2023-07-03 07:37 UTC, LexLippi approved these changes
Привет!

Отличная работа!

Желаю удачи в следующих српинтах!

2023-07-11 10:45 UTC, KolesnikovaEV commented
Привет! Спасибо за комментарии, вроде все исправила)

2023-07-11 10:45 UTC, merged