Выполнено ТЗ, 16 спринт
KolesnikovaEV/java-shareit pull request #4
Opened 2023-08-09 10:07 UTC by KolesnikovaEV

2023-08-12 11:19 UTC, LexLippi requested changes
Привет!

Отличная работа!

Есть пара небольших замечаний и советов.

Желаю удачи!

2023-08-12 11:19 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/gate/request/ItemRequestController.java
> +            @Positive @RequestParam(name = "size", defaultValue = "20") Integer size) {
нет большой необходимости в использовании в данном случае поля `name`, так как оно идентично названию переменных, и автоматически будет взято из имени переменных

2023-08-12 11:19 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/gate/item/dto/ItemDtoForItemRequest.java
> +@RequiredArgsConstructor
В этом нет особого смысла, так как эта аннотация уже содержится внутри `Data`:

https://projectlombok.org/features/Data

2023-08-12 11:19 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/gate/booking/model/BookingState.java
> +    UNSUPPORTED_STATUS;
Кажется, что нет большой необходимости в этом статусе

2023-08-12 11:19 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/gate/booking/dto/CreateBookingDto.java
> +    //@FutureOrPresent(groups = {CreateObject.class})
Это лучше удалять

2023-08-12 12:14 UTC, KolesnikovaEV commented
Спасибо за ревью! Вроде все поправила)

2023-08-13 20:50 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи с дипломным проектом!

2023-08-27 19:03 UTC, merged